---
platform: linux
image_resource:
  type: docker-image
  source: {repository: golang}
run:
  path: sh
  args:
  - -exc
  - |
    chmod +x ./release-rc/super_*_linux_amd64
    ./release-rc/super_*_linux_amd64&
    ./rabay-app/scripts/test_integeration.sh http://127.0.0.1:8080
    kill -9 `pgrep super_`
inputs:
  - name: rabay-app
  - name: release-rc
