---
resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: jtarchie/pr

resources:
  - name: rabay-app
    type: pull-request
    source: 
      repo: franklinrabay/concourse-tutorial
      access_token: {{github_token}}

jobs:
  - name: Testing
    plan:
    - get: rabay-app
      trigger: true
    - put: rabay-app
      params: {path: concourse-tutorial, context: lint & unit test, status: pending}
    - aggregate:
      - task: Linting
        file: rabay-app/tutorial/scenario.2/4-deconstructing/tasks/lint.yml
      
      - task: Testing
        file: rabay-app/tutorial/scenario.2/4-deconstructing/tasks/unit.yml
  
  - name: Compiling
    plan:
    - get: rabay-app
      passed: ["Testing"]
      trigger: true

    - task: Compile this SHIT!
      config: 
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: golang}
        run:
          path: sh
          args:
          - -exc
          - |
            ./scripts/go_deps.sh
            ./scripts/go_build.sh linux 0.0.1
            mv super_*_linux_amd64 ../artifact
          dir: rabay-app
        inputs:
          - name: rabay-app
        outputs:
          - name: artifact

    - task: INTEGRATIONNNNNN >D
      config: 
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: golang}
        run:
          path: sh
          args:
          - -exc
          - |
            ../artifact/super_*_linux_amd64&
            ./scripts/test_integeration.sh http://127.0.0.1:8080
            kill -9 `pgrep super_`
          dir: rabay-app
        inputs:
          - name: rabay-app
          - name: artifact

    - task: listing data of rabay-app
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: ubuntu}
        run:
          path: ls
          args: ["-l"]
        inputs: 
          - name: rabay-app