---
resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: jtarchie/pr

resources:
  - name: rabay-app
    type: pull-request
    source: 
      repo: franklinrabay/concourse-tutorial
      access_token: {{github_token}}
  
  - name: release-rc
    type: github-release
    source:
      user: franklinrabay
      repository: concourse-tutorial
      access_token: {{github_token}}
      pre_release: True
  
  - name: semantic
    type: semver
    source:
        driver: git
        initial_version: 0.0.1
        uri: https://{{github_token}}@github.com/franklinrabay/concourse-tutorial
        branch: version
        file: version

jobs:
  - name: Testing
    plan:
    - get: rabay-app
      trigger: true
    - put: rabay-app
      params: {path: rabay-app, context: lint & unit test, status: pending}
    - aggregate:
      - task: Linting
        file: rabay-app/tutorial/scenario.2/4-deconstructing/tasks/lint.yml
      
      - task: Testing
        file: rabay-app/tutorial/scenario.2/4-deconstructing/tasks/unit.yml

  - name: Bump RC
    plan:
    - get: rabay-app
      passed: ["Testing"]
      trigger: true

    - put: semantic
      params:
        pre: rc
  
  - name: Compiling
    plan:
    - get: rabay-app
      passed: ["Bump RC"]
      trigger: true

    - aggregate:
      - task: build linux
        file: rabay-app/tutorial/scenario.4/1-multi-os/tasks/build_linux.yml

      - task: build darwin
        file: rabay-app/tutorial/scenario.4/1-multi-os/tasks/build_darwin.yml

      - task: build windows
        file: rabay-app/tutorial/scenario.4/1-multi-os/tasks/build_windows.yml
      
    - put: release-rc
      params:
        name: rabay-app/tutorial/scenario.4/2-releases/version
        tag : rabay-app/tutorial/scenario.4/2-releases/version
        tag_prefix: v
        globs:
          - artifact_linux/super_*_linux_amd64
          - artifact_windows/super_*_windows_amd64
          - artifact_darwin/super_*_darwin_amd64
  
  - name: Integeration test
    plan:

    - get: release-rc
      passed: ["Compiling"]
      params:
        globs:
          - super_*_linux_amd64

    - get: rabay-app
      passed: ["Compiling"]
      trigger: true

    - task: integeration test
      file: rabay-app/tutorial/scenario.4/2-releases/tasks/integeration.yml
      